-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[sp_ASR_AbsenceBreakdown_Calculate](
	@pdblResult                       float OUTPUT,
	@pfMonTotal                      float OUTPUT,
	@pfTueTotal                      float OUTPUT,
	@pfWedTotal                      float OUTPUT,
	@pfThuTotal                      float OUTPUT,
	@pfFriTotal                      float OUTPUT,
	@pfSatTotal                      float OUTPUT,
	@pfSunTotal                      float OUTPUT,
	@pdtStartDate                     datetime,
	@psStartSession                   varchar(255),
	@pdtEndDate                       datetime,
	@psEndSession                     varchar(255),
	@iPersonnelID                     int
	) 
AS 
BEGIN
	RETURN 0
END