-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[sp_ASR_TBCheckUnavailability] (
	@plngCourseRecordID int,
	@plngEmployeeRecordID int,
	@piReturnCode int OUTPUT
)
AS
	RETURN 0