-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[sp_ASRFn_AbsenceDuration](
	 @pdblResult                       float OUTPUT,
	 @pdtStartDate                     datetime,
	 @psStartSession                   varchar(255),
	 @pdtEndDate                       datetime,
	 @psEndSession                     varchar(255),
	 @iPersonnelID                     int
	 ) 
AS 
	RETURN 0