-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[spASRSysWorkflowParentRecord]
(
	@piChildTableID integer,
	@piChildRecordID integer,
	@piParentTableID integer,
	@piParentRecordID integer OUTPUT
)
AS
BEGIN
	RETURN 0
END