-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[spASRSendMail](
	@hResult int OUTPUT,
	@To varchar(MAX),
	@CC varchar(MAX),
	@BCC varchar(MAX),
	@Subject varchar(MAX),
	@Message varchar(MAX),
	@Attachment varchar(MAX))
AS
	RETURN 0;