-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[spASRSysEmailAddr] (
	@param1 varchar(MAX) OUTPUT,
	@param2 int,
	@param3	int)
AS
	RETURN 0;
