-- This stored procedure is a code stub and will be regenerated by a Security Manager save.
CREATE PROCEDURE spASRGenerateSelfServiceLogins(@logins AS SelfServiceType READONLY)
AS
BEGIN
	SET NOCOUNT ON;
END