-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[spASRSysGetCurrentUserRecordID]
    @piRecordID integer OUTPUT,
    @piRecordCount integer OUTPUT,
		@psRecordDescription nvarchar(MAX) OUTPUT
AS
BEGIN
	RETURN 0
END
