-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[spASRSysEmailAddr] (
	@hResult varchar(8000) OUTPUT,
	@EmailID int,
	@recordID	int)
AS
	RETURN 0;
