-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE dbo.[spASRWorkflowGetValidLoginsForStep] (
	@instanceID int,
	@elementId int,
	@requiresAuthorization bit OUTPUT)
AS
BEGIN
	SELECT '' AS [Email], '' AS [Login] WHERE 3 = 4
END

