-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[spASRIntGetCancelCourseDate]
	@pfError bit OUTPUT,
	@piRecID integer,
	@pfCancelDate bit OUTPUT
AS
BEGIN
	RETURN 0
END