-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE PROCEDURE [dbo].[spASRWorkflowGetSelfServiceRecordID]
	@piRecordID	integer OUTPUT,
	@piRecordCount integer OUTPUT
AS
BEGIN
	SET @piRecordID = 0;
END
