-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE FUNCTION [dbo].[udfASRIntOrgChartGetTopLevelID](
  @StaffRecordID integer
  )
RETURNS integer
AS
BEGIN
  RETURN 0;
END