-- This stored procedure is a code stub and will be regenerated by a System Manager save.
CREATE FUNCTION [dbo].[udfASRGetWorkflowDelegatedRecords]
(
	@psOriginalRecipient varchar(MAX)
)
RETURNS @returntable TABLE
(
	id integer, 
	emailAddress varchar(MAX), 
	delegated bit, 
	delegatedTo varchar(MAX)
)
AS
BEGIN

	RETURN

END


