//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHRTestToLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRSysWorkflowElementValidation
    {
        public int ID { get; set; }
        public int ElementID { get; set; }
        public int ExprID { get; set; }
        public short Type { get; set; }
        public string Message { get; set; }
    }
}
