//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHRTestToLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRSysWorkflowLinks
    {
        public int ID { get; set; }
        public int WorkflowID { get; set; }
        public int StartElementID { get; set; }
        public int EndElementID { get; set; }
        public Nullable<int> StartOutboundFlowCode { get; set; }
    }
}
