//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHRNexus.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbuser_Languages
    {
        public int ID { get; set; }
        public Nullable<int> ID_1 { get; set; }
        public Nullable<decimal> Language_Level { get; set; }
        public string Language_Name { get; set; }
        public string Spoken_Fluency { get; set; }
        public string Written_Fluency { get; set; }
        public Nullable<int> updflag { get; set; }
        public string C_description { get; set; }
        public Nullable<bool> C_deleted { get; set; }
        public Nullable<System.DateTime> C_deleteddate { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
