'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class [Default]

   '''<summary>
   '''frmMain control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents frmMain As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''tsm control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents tsm As Global.AjaxControlToolkit.ToolkitScriptManager

   '''<summary>
   '''divInput control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents divInput As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''pnlInput control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlInput As Global.System.Web.UI.UpdatePanel

   '''<summary>
   '''pnlInputDiv control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlInputDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''pnlTabsDiv control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents pnlTabsDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''btnDoFilter control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnDoFilter As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''hdnMobileLookupFilter control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnMobileLookupFilter As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnCount_Errors control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnCount_Errors As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnCount_Warnings control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnCount_Warnings As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnOverrideWarnings control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnOverrideWarnings As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnLastButtonClicked control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnLastButtonClicked As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnNoSubmissionMessage control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnNoSubmissionMessage As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnFollowOnForms control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnFollowOnForms As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnErrorMessage control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnErrorMessage As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnSiblingForms control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnSiblingForms As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnSubmissionMessage_1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnSubmissionMessage_1 As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnSubmissionMessage_2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnSubmissionMessage_2 As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnSubmissionMessage_3 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnSubmissionMessage_3 As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''errorMessagePanel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents errorMessagePanel As Global.System.Web.UI.WebControls.Panel

   '''<summary>
   '''lblErrors control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''bulletErrors control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents bulletErrors As Global.System.Web.UI.WebControls.BulletedList

   '''<summary>
   '''lblWarnings control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblWarnings As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''bulletWarnings control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents bulletWarnings As Global.System.Web.UI.WebControls.BulletedList

   '''<summary>
   '''overrideWarning control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents overrideWarning As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''hdnDefaultPageNo control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnDefaultPageNo As Global.System.Web.UI.WebControls.HiddenField
End Class
