'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FileUpload

   '''<summary>
   '''frmFileUpload control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents frmFileUpload As Global.System.Web.UI.HtmlControls.HtmlForm

   '''<summary>
   '''lblErrors control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblErrors As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''bulletErrors control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents bulletErrors As Global.System.Web.UI.WebControls.BulletedList

   '''<summary>
   '''lblFileUploadPrompt control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblFileUploadPrompt As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''FileUpload1 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents FileUpload1 As Global.System.Web.UI.HtmlControls.HtmlInputFile

   '''<summary>
   '''btnFileUpload control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnFileUpload As Global.System.Web.UI.HtmlControls.HtmlInputButton

   '''<summary>
   '''btnClear control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnClear As Global.System.Web.UI.HtmlControls.HtmlInputButton

   '''<summary>
   '''btnCancel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnCancel As Global.System.Web.UI.HtmlControls.HtmlInputButton

   '''<summary>
   '''hdnCount_Errors control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnCount_Errors As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnElementID control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnElementID As Global.System.Web.UI.WebControls.HiddenField

   '''<summary>
   '''hdnExitMode control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents hdnExitMode As Global.System.Web.UI.WebControls.HiddenField
End Class
