'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Home

   '''<summary>
   '''lblWelcome control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblWelcome As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblNothingTodo control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblNothingTodo As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''workflowList control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents workflowList As Global.System.Web.UI.HtmlControls.HtmlGenericControl

   '''<summary>
   '''btnTodoList control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnTodoList As Global.System.Web.UI.WebControls.HyperLink

   '''<summary>
   '''lblWFCount control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblWFCount As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''btnChangePwd control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnChangePwd As Global.System.Web.UI.WebControls.HyperLink

   '''<summary>
   '''btnLogout control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnLogout As Global.System.Web.UI.WebControls.LinkButton
End Class
