Public Module Constants
	Public Const DEADLOCK_ERRORNUMBER = -2147467259
	Public Const DEADLOCK_MESSAGESTART = "YOUR TRANSACTION (PROCESS ID #"
	Public Const DEADLOCK_MESSAGEEND = ") WAS DEADLOCKED WITH ANOTHER PROCESS AND HAS BEEN CHOSEN AS THE DEADLOCK VICTIM. RERUN YOUR TRANSACTION."
	Public Const DEADLOCK2_MESSAGESTART = "TRANSACTION (PROCESS ID "
	Public Const DEADLOCK2_MESSAGEEND = ") WAS DEADLOCKED ON "
	Public Const SQLMAILNOTSTARTEDMESSAGE = "SQL MAIL SESSION IS NOT STARTED."
End Module
