Namespace Enums
	Public Enum ExpressionValueTypes
		giEXPRVALUE_UNDEFINED = 0
		giEXPRVALUE_CHARACTER = 1
		giEXPRVALUE_NUMERIC = 2
		giEXPRVALUE_LOGIC = 3
		giEXPRVALUE_DATE = 4
		giEXPRVALUE_TABLEVALUE = 5
		giEXPRVALUE_OLE = 6
		giEXPRVALUE_PHOTO = 7
		giEXPRVALUE_BYREF_UNDEFINED = 100
		giEXPRVALUE_BYREF_CHARACTER = 101
		giEXPRVALUE_BYREF_NUMERIC = 102
		giEXPRVALUE_BYREF_LOGIC = 103
		giEXPRVALUE_BYREF_DATE = 104
		giEXPRVALUE_BYREF_TABLEVALUE = 105 ' Not used.
		giEXPRVALUE_BYREF_OLE = 106	' Not used.
		giEXPRVALUE_BYREF_PHOTO = 107	' Not used.
	End Enum
End Namespace
