Namespace Enums
	Public Enum ExpressionTypes
		giEXPR_UNKNOWNTYPE = 0
		giEXPR_COLUMNCALCULATION = 1
		giEXPR_GOTFOCUS = 2	' Not used.
		giEXPR_RECORDVALIDATION = 3
		giEXPR_DEFAULTVALUE = 4	' Not used.
		giEXPR_STATICFILTER = 5
		giEXPR_PAGEBREAK = 6 ' Not used.
		giEXPR_ORDER = 7 ' Not used.
		giEXPR_RECORDDESCRIPTION = 8
		giEXPR_VIEWFILTER = 9
		giEXPR_RUNTIMECALCULATION = 10
		giEXPR_RUNTIMEFILTER = 11
		giEXPR_EMAIL = 12	' System Manager Only
		giEXPR_LINKFILTER = 13 ' System Manager Only
		giEXPR_UTILRUNTIMEFILTER = 14	'Import filter
		giEXPR_MATCHJOINEXPRESSION = 15
		giEXPR_MATCHSCOREEXPRESSION = 16
		giEXPR_MATCHWHEREEXPRESSION = 17
		giEXPR_RECORDINDEPENDANTCALC = 18
		giEXPR_OUTLOOKFOLDER = 19	'System Manager Only
		giEXPR_OUTLOOKSUBJECT = 20 'System Manager Only
		giEXPR_WORKFLOWCALCULATION = 21	'System Manager Only
		giEXPR_WORKFLOWSTATICFILTER = 22 'System Manager Only
		giEXPR_WORKFLOWRUNTIMEFILTER = 23	'System Manager Only
	End Enum
End Namespace

