Namespace Enums
	Public Enum ExpressionComponentTypes
		giCOMPONENT_FIELD = 1
		giCOMPONENT_FUNCTION = 2
		giCOMPONENT_CALCULATION = 3
		giCOMPONENT_VALUE = 4
		giCOMPONENT_OPERATOR = 5
		giCOMPONENT_TABLEVALUE = 6
		giCOMPONENT_PROMPTEDVALUE = 7
		giCOMPONENT_CUSTOMCALC = 8 ' Not used.
		giCOMPONENT_EXPRESSION = 9
		giCOMPONENT_FILTER = 10
		giCOMPONENT_WORKFLOWVALUE = 11
		giCOMPONENT_WORKFLOWFIELD = 12
	End Enum
End Namespace

