Namespace Enums
	Public Enum ExprValidationCodes
		giEXPRVALIDATION_NOERRORS = 0
		giEXPRVALIDATION_MISSINGOPERAND = 1
		giEXPRVALIDATION_SYNTAXERROR = 2
		giEXPRVALIDATION_EXPRTYPEMISMATCH = 3
		giEXPRVALIDATION_UNKNOWNERROR = 4
		giEXPRVALIDATION_OPERANDTYPEMISMATCH = 5
		giEXPRVALIDATION_PARAMETERTYPEMISMATCH = 6
		giEXPRVALIDATION_NOCOMPONENTS = 7
		giEXPRVALIDATION_PARAMETERSYNTAXERROR = 8
		giEXPRVALIDATION_PARAMETERNOCOMPONENTS = 9
		giEXPRVALIDATION_FILTEREVALUATION = 10
		giEXPRVALIDATION_SQLERROR = 11
		giEXPRVALIDATION_ASSOCSQLERROR = 12
		giEXPRVALIDATION_CYCLIC = 13
	End Enum
End Namespace
