Attribute VB_Name = "modOvernightProcess"
Option Explicit

Public glngOvernightJobTime As Long

Public Function CreateOvernightProcess(palngExpressions As Variant, pfRefreshDatabase As Boolean) As Boolean

  'Step 1 - Set flags
  'Step 2 - Update column calcs
  'Step 3 - Unset flags
  'Step 4 - Email/diary processing

  On Error GoTo ErrorTrap

  Dim fOK As Boolean
  Dim strScriptPath As String
  Dim strFileName As String
  
  If Application.ChangedOvernightJobSchedule Then
    'Make sure that we run the script for the overnight job Schedule
    strFileName = "OvernightJob.sql"
    strScriptPath = gsApplicationPath & "\Update Scripts\" & strFileName
    
    RunOvernightScript strScriptPath
  End If
  
  fOK = gobjHRProEngine.Script.ScriptOvernightStep2

  If fOK Then fOK = OvernightJob1       'Step 1
  If fOK Then fOK = OvernightJob3       'Step 3
  If fOK Then fOK = OvernightJob4       'Step 4

  ' Reindex and update stats job
  If fOK Then fOK = OvernightJob5         'Always refresh Step 5 !!!

TidyAndExit:
  If fOK = False Then
    OutputError "Error creating overnight process"
  End If
  CreateOvernightProcess = fOK
Exit Function


ErrorTrap:
  fOK = False
  Resume TidyAndExit

End Function

Private Function RunOvernightScript(pstrFileName As String) As Boolean

  Dim sUpdateScript As String
  Dim sReadString As String

  sUpdateScript = vbNullString

  Open pstrFileName For Input As #1
  Do While Not EOF(1)
    Line Input #1, sReadString
    sUpdateScript = sUpdateScript & sReadString & vbNewLine
  Loop
  Close #1

  If sUpdateScript <> vbNullString Then
    'Set rdoTempCon = rdoEnv.OpenConnection("", rdDriverNoPrompt, False, sConnect)
    gADOCon.Execute sUpdateScript, , adExecuteNoRecords
  End If

End Function

Private Function OvernightJob1() As Boolean

  Const strOvernightSP As String = "spASRSysOvernightStep1"
  Dim strSQL As String
  
  DropExistingJobStep (strOvernightSP)

    'AE20080214 Fault #12726 - Nested Trigger check is now in the UPD_ triggers
  strSQL = "/* ------------------------------------------------------------------------------- */" & vbNewLine & _
    "/* system stored procedure.                  */" & vbNewLine & _
    "/* Automatically generated by the System Manager.   */" & vbNewLine & _
    "/* ------------------------------------------------------------------------------- */" & vbNewLine & _
    "CREATE PROCEDURE dbo." & strOvernightSP & " AS" & vbNewLine & _
    "BEGIN" & vbNewLine & _
    "    DECLARE @sDBName     nvarchar(100)," & vbNewLine & _
    "            @NVarCommand nvarchar(MAX);" & vbNewLine & vbNewLine & _
    "    SELECT @sDBName = DB_NAME()" & vbNewLine & vbNewLine & _
    "    /* This sets all of the flags prior to updating date dependant columns */" & vbNewLine & _
    "    DELETE FROM ASRSYSSystemSettings WHERE [Section] = 'database' and [SettingKey] = 'updatingdatedependantcolumns'" & vbNewLine & vbNewLine & _
    "    INSERT ASRSYSSystemSettings([Section],[SettingKey],[SettingValue])" & vbNewLine & _
    "    VALUES('database','updatingdatedependantcolumns',1)" & vbNewLine & vbNewLine & _
    "    SELECT @NVarCommand = 'ALTER DATABASE ['+ @sDBName + '] SET RECURSIVE_TRIGGERS OFF';" & vbNewLine & _
    "    EXEC sp_executesql @NVarCommand;" & _
    "END"
    
  gADOCon.Execute strSQL, , adExecuteNoRecords

  OvernightJob1 = True

End Function

Private Function OvernightJob3() As Boolean

  Const strOvernightSP As String = "spASRSysOvernightStep3"
  Dim strSQL As String
  
  DropExistingJobStep (strOvernightSP)
  
    'AE20080214 Fault #12726 - Nested Trigger check is now in the UPD_ triggers
  strSQL = "/* ------------------------------------------------------------------------------- */" & vbNewLine & _
    "/* system stored procedure.                  */" & vbNewLine & _
    "/* Automatically generated by the System Manager.   */" & vbNewLine & _
    "/* ------------------------------------------------------------------------------- */" & vbNewLine & _
    "CREATE PROCEDURE [dbo].[" & strOvernightSP & "] AS" & vbNewLine & _
    "BEGIN" & vbNewLine & _
    "    DECLARE @sDBName nvarchar(MAX)" & vbNewLine & vbNewLine & _
    "    SELECT @sDBName = db_name()" & vbNewLine & vbNewLine & _
    "    /* This unsets all of the flags after updating date dependant columns */" & vbNewLine & _
    "    DELETE FROM ASRSYSSystemSettings WHERE [Section] = 'database' and [SettingKey] = 'updatingdatedependantcolumns'" & vbNewLine & vbNewLine & _
    "    INSERT ASRSYSSystemSettings([Section],[SettingKey],[SettingValue])" & vbNewLine & _
    "    VALUES('database','updatingdatedependantcolumns',0)" & vbNewLine & vbNewLine & _
    "END"
    
  gADOCon.Execute strSQL, , adExecuteNoRecords

  OvernightJob3 = True

End Function


Private Function OvernightJob4() As Boolean

  Const strOvernightSP As String = "spASRSysOvernightStep4"
  Dim strSQL As String
  
  DropExistingJobStep (strOvernightSP)

  strSQL = "/* ------------------------------------------------------------------------------- */" & vbNewLine & _
    "/* system stored procedure.                  */" & vbNewLine & _
    "/* Automatically generated by the System Manager.   */" & vbNewLine & _
    "/* ------------------------------------------------------------------------------- */" & vbNewLine & _
  "CREATE PROCEDURE [dbo].[" & strOvernightSP & "] AS" & vbNewLine & _
    "BEGIN" & vbNewLine & _
    "    -- Overnight Email Processing" & vbNewLine & _
    "    EXEC sp_ASRPurgeRecords 'EMAIL', 'ASRSysEmailQueue', 'DateDue'" & vbNewLine & _
    "    EXEC spASREmailRebuild;" & vbNewLine & _
    "    EXEC spASREmailBatch;" & vbNewLine & vbNewLine & _
    "    -- Overnight Diary Processing" & vbNewLine & _
    "    EXEC sp_executeSQL sp_ASRDiaryPurge;" & vbNewLine & vbNewLine & _
    IIf(Application.WorkflowModule, _
    "    -- Overnight Workflow Processing" & vbNewLine & _
    "    EXEC sp_executeSQL spASRWorkflowRebuild;" & vbNewLine & vbNewLine, vbNullString) & _
    "    -- Overnight Log Purging" & vbNewLine & _
    "    EXEC sp_executeSQL sp_ASRAuditLogPurge;" & vbNewLine & _
    "    EXEC sp_executeSQL sp_AsrEventLogPurge;" & vbNewLine & vbNewLine
    
  strSQL = strSQL & _
    "    -- Update Overnight Job Log" & vbNewLine & _
    "    DELETE from ASRSysSystemSettings" & vbNewLine & _
    "    WHERE [Section] = 'overnight' and [SettingKey] = 'last completed';" & vbNewLine & _
    "    INSERT ASRSysSystemSettings([Section], [SettingKey], [SettingValue])" & vbNewLine & _
    "    VALUES('overnight', 'last completed', convert(varchar,getdate(),103)+' '+convert(varchar,getdate(),108));" & vbNewLine & vbNewLine & _
    "    -- Update the system wide headcounts" & vbNewLine & _
    "    EXEC sp_executeSQL spASRCalculateHeadcounts;" & vbNewLine & _
    "END"

'  AE20071219 Fault #12731
'  If Application.WorkflowModule Then
'    strSQL = strSQL & _
'      "    EXEC spASRWorkflowRebuild" & vbNewLine
'  End If
  
'  strSQL = strSQL & _
'    "END"
  
  gADOCon.Execute strSQL, , adExecuteNoRecords

  OvernightJob4 = True

End Function

Private Function DropExistingJobStep(strOvernightSP As String) As Boolean

  Dim strSQL As String

  On Error GoTo ErrorTrap

  strSQL = "IF EXISTS" & _
    " (SELECT Name" & _
    "   FROM sysobjects" & _
    "   WHERE id = object_id('" & strOvernightSP & "')" & _
    "     AND sysstat & 0xf = 4)" & _
    " DROP PROCEDURE " & strOvernightSP
    
  gADOCon.Execute strSQL, , adExecuteNoRecords

Exit Function

ErrorTrap:
  OutputError "Error Removing overnight process"

End Function

' Automatic reindex job
Private Function OvernightJob5() As Boolean

  Const strOvernightSP As String = "spASRSysOvernightStep5"
  Dim strSQL As String
  
  DropExistingJobStep (strOvernightSP)

  strSQL = "/* ------------------------------------------------------------------------------- */" & vbNewLine & _
    "/* system stored procedure.                  */" & vbNewLine & _
    "/* Automatically generated by the System Manager.   */" & vbNewLine & _
    "/* ------------------------------------------------------------------------------- */" & vbNewLine & _
    "CREATE PROCEDURE [dbo].[" & strOvernightSP & "] AS" & vbNewLine & _
    "BEGIN" & vbNewLine & _
    "    DECLARE @iCount int;" & vbNewLine & vbNewLine
    
  strSQL = strSQL & "    EXEC [dbo].[spASRGetCurrentUsers]" & vbNewLine & _
    "    IF @@ROWCOUNT = 0" & vbNewLine & _
    "    BEGIN" & vbNewLine & _
    "        -- Tidy up temporary objects" & vbNewLine & _
    "        EXEC sp_executeSQL spASRDropTempObjects;" & vbNewLine & vbNewLine & _
    "        -- Defragment indexes" & vbNewLine & _
    "        EXEC dbo.spASRDefragIndexes;" & vbNewLine & vbNewLine & _
    "        -- Update statistics" & vbNewLine & _
    "        EXEC sp_executeSQL spASRUpdateStatistics;" & vbNewLine & vbNewLine & _
    "        -- Optimise the record save for single record" & vbNewLine & _
    "        EXEC sp_executeSQL spadmin_optimiserecordsave;" & vbNewLine & _
    "    END" & vbNewLine & vbNewLine & _
    "    -- Clear automagic self service logins" & vbNewLine & _
    "    EXEC sp_executeSQL spASRDeleteExpiredSelfServiceLogins;" & vbNewLine & vbNewLine
  
  strSQL = strSQL & "END"
  
  gADOCon.Execute strSQL, , adExecuteNoRecords
  
  OvernightJob5 = True

End Function


