Namespace Code
	Public Class InputValidation

		Public Shared ListOfActions As List(Of String)
		Public Shared ListOfUtilTypes As List(Of String)

		Public Shared Sub Initialise()

			Dim txtActions() As String = {
				"ABSENCEBREAKDOWNALL", _
				"ABSENCEBREAKDOWNREC", _
				"ADDEXPRCOMPONENT", _
				"ADDFROMWAITINGLIST", _
				"ADDFROMWAITINGLISTERROR", _
				"ADDFROMWAITINGLISTSUCCESS", _
				"ALL", _
				"BOOKCOURSE", _
				"BOOKCOURSEERROR", _
				"BOOKCOURSESUCCESS", _
				"BRADFORDFACTORALL", _
				"BRADFORDFACTORREC", _
				"BULKBOOKINGERROR", _
				"BULKBOOKINGSUCCESS", _
				"CALCULATIONS", _
				"CALENDARREPORTS", _
				"CALENDARREPORTSREC", _
				"CANCEL", _
				"CANCELBOOKING", _
				"CANCELBOOKING_1", _
				"CANCELCOURSE", _
				"CANCELCOURSE_1", _
				"CANCELCOURSE_2", _
				"CLEAR", _
				"CLEARFILTER", _
				"COPY", _
				"CROSSTABS", _
				"NINEBOXGRID", _
				"CUSTOMREPORTS", _
				"DEFAULT", _
				"DELETE", _
				"EDITEXPRCOMPONENT", _
				"EVENTLOG", _
				"EXIT", _
				"FILTER", _
				"FILTERS", _
				"FIND", _
				"GETBULKBOOKINGSELECTION", _
				"GETEXPRESSIONRETURNTYPES", _
				"GETPICKLISTSELECTION", _
				"INSERTEXPRCOMPONENT", _
				"LINK", _
				"LINKOLE", _
				"LOAD", _
				"LOADCALENDARREPORTCOLUMNS", _
				"LOADEVENTLOG", _
				"LOADEVENTLOGUSERS", _
				"LOADEXPRFIELDCOLUMNS", _
				"LOADEXPRLOOKUPCOLUMNS", _
				"LOADEXPRLOOKUPVALUES", _
				"LOADFIND", _
				"LOADLOOKUPFIND", _
				"LOADTRANSFERCOURSE", _
				"LOADBOOKCOURSE", _
				"LOADADDFROMWAITINGLIST", _
				"LOADTRANSFERBOOKING", _
				"LOADREPORTCOLUMNS", _
				"LOCATE", _
				"LOCATEID", _
				"LOGOFF", _
				"LOOKUP", _
				"MAILMERGE", _
				"MOVEFIRST", _
				"MOVENEXT", _
				"MOVELAST", _
				"MOVEPREVIOUS", _
				"NEW", _
				"PARENT", _
				"PICKLIST", _
				"QUICKFIND", _
				"REFRESHFINDAFTERDELETE", _
				"REFRESHFINDAFTERINSERT", _
				"RELOAD", _
				"SAVE", _
				"SAVEERROR", _
				"SELECTADDFROMWAITINGLIST_1", _
				"SELECTADDFROMWAITINGLIST_2", _
				"SELECTADDFROMWAITINGLIST_3", _
				"SELECTBOOKCOURSE_1", _
				"SELECTBOOKCOURSE_2", _
				"SELECTBOOKCOURSE_3", _
				"SELECTBULKBOOKINGS", _
				"SELECTBULKBOOKINGS_2", _
				"SELECTCOMPONENT", _
				"SELECTFILTER", _
				"SELECTIMAGE", _
				"SELECTLINK", _
				"SELECTLOOKUP", _
				"SELECTOLE", _
				"SELECTORDER", _
				"SELECTTRANSFERBOOKING_1", _
				"SELECTTRANSFERBOOKING_2", _
				"SELECTTRANSFERCOURSE", _
				"STDRPT_ABSENCECALENDAR", _
				"STDREPORT_DATEPROMPT", _
				"TRANSFERBOOKING", _
				"TRANSFERBOOKINGERROR", _
				"TRANSFERBOOKINGSUCCESS", _
				"TRANSFERCOURSE", _
				"VIEW", _
				"WORKFLOW", _
				"WORKFLOWOUTOFOFFICE", _
				"WORKFLOWPENDINGSTEPS"
			}

			ListOfActions = New List(Of String)(txtActions)

			Dim txtUtilTypes() As String = {
				"UTLBATCHJOB", _
				"UTLCROSSTAB", _
				"UTLCUSTOMREPORT", _
				"UTLDATATRANSFER", _
				"UTLEXPORT", _
				"UTLGLOBALADD", _
				"UTLGLOBALDELETE", _
				"UTLGLOBALUPDATE", _
				"UTLIMPORT", _
				"UTLMAILMERGE", _
				"UTLPICKLIST", _
				"UTLFILTER", _
				"UTLCALCULATION", _
				"UTLORDER", _
				"UTLMATCHREPORT", _
				"UTLABSENCEBREAKDOWN", _
				"UTLBRADFORDFACTOR", _
				"UTLCALENDARREPORT", _
				"UTLLABEL", _
				"UTLLABELTYPE", _
				"UTLRECORDPROFILE", _
				"UTLEMAILADDRESS", _
				"UTLEMAILGROUP", _
				"UTLSUCCESSION", _
				"UTLCAREER", _
				"UTLWORKFLOW", _
				"UTLWORKFLOWPENDINGSTEPS", _
				"UTLORDERDEFINITION", _
				"UTLDOCUMENTMAPPING", _
				"UTLREPORTPACK", _
				"UTLTURNOVER", _
				"UTLSTABILITY", _
				"UTLSCREEN", _
				"UTLTABLE", _
				"UTLCOLUMN", _
				"UTLNINEBOXGRID", _
				"UTLABSENCEBREAKDOWNCONFIGURATION"
			}

			ListOfUtilTypes = New List(Of String)(txtUtilTypes)

		End Sub





	End Class
End Namespace