Option Explicit On

Namespace ScriptDB

  Public Module ScriptFunctions

#Region "Numeric Functions"

#End Region

    Public Function ConvertCurrency() As Boolean

      Dim bOK As Boolean = True
      Dim sSQL As String = vbNullString
      Dim objConversionTable As Things.Table
      Dim objNameColumn As Things.Column
      Dim objValueColumn As Things.Column
      Dim objDecimalsColumn As Things.Column


      Dim iKeyID As HCMGuid

      Dim sObjectName As String

      objConversionTable = Globals.ModuleSetup.GetSetting("MODULE_CURRENCY", "Param_ConversionTable").Table

      iKeyID = Globals.ModuleSetup.GetSetting("MODULE_CURRENCY", "Param_CurrencyNameColumn").Value
      objNameColumn = objConversionTable.Column(iKeyID)

      iKeyID = Globals.ModuleSetup.GetSetting("MODULE_CURRENCY", "Param_ConversionValueColumn").Value
      objValueColumn = objConversionTable.Column(iKeyID)

      iKeyID = Globals.ModuleSetup.GetSetting("MODULE_CURRENCY", "Param_DecimalColumn").Value
      objDecimalsColumn = objConversionTable.Column(iKeyID)

      sObjectName = "udfsys_convertcurrency"
      sSQL = String.Format("/* ------------------------------------------------- */" & vbNewLine & _
              "/* HR Pro Currency module user defined function.                  */" & vbNewLine & _
              "/* Automatically generated by the Advanced DB Scripting Engine.   */" & vbNewLine & _
              "/* -------------------------------------------------------------- */" & vbNewLine & _
              "CREATE FUNCTION dbo.[{0}] (" & vbNewLine & _
              "   @currency numeric(38,8)," & vbNewLine & _
              "   @from {5}," & vbNewLine & _
              "   @to {5})" & vbNewLine & _
              "RETURNS numeric(38,8)" & vbNewLine & _
              "AS " & vbNewLine & _
              "BEGIN" & vbNewLine & vbNewLine & _
              "    DECLARE @result numeric(38,8);" & vbNewLine & _
              "    SELECT @result = ROUND(ISNULL((@currency / NULLIF((SELECT [{2}] FROM dbo.[{1}] WHERE [{3}] = @from),0))" & vbNewLine &
              "                      * " & vbNewLine & _
              "                     (SELECT [{2}] FROM dbo.[{1}] WHERE [{3}] = @to), 0)," & vbNewLine & _
              "                         ISNULL((SELECT [{4}] FROM dbo.[{1}] WHERE [{3}] = @to), 0))" & vbNewLine & vbNewLine & _
              "    RETURN ISNULL(@result,0);" & vbNewLine & _
              "END", sObjectName, objConversionTable.Name, objValueColumn.Name, objNameColumn.Name, objDecimalsColumn.Name _
                , objNameColumn.DataTypeSyntax)
      ScriptDB.DropUDF("dbo", sObjectName)
      bOK = CommitDB.ScriptStatement(sSQL)

      Return bOK

    End Function



  End Module


End Namespace
