Attribute VB_Name = "modSave_Fusion"
Option Explicit

Public Function CreateFusionExpressionSPs(pfRefreshDatabase As Boolean) As Boolean

  On Error GoTo ErrorTrap

  Dim rsProcedures As DAO.Recordset
  Dim rsMapData As DAO.Recordset
  Dim sSQL As String
  Dim strSPCode As String
  Dim bOK As Boolean
  Dim sProcedureName As String

  bOK = True
  
  sSQL = "SELECT FusionFieldID, FusionTypeID FROM tmpFusionFieldDefinitions WHERE ConvertData = true"
  Set rsProcedures = daoDb.OpenRecordset(sSQL, dbOpenForwardOnly, dbReadOnly)

  Do While Not (rsProcedures.EOF)

    sProcedureName = "spASRFusionExpr_" & rsProcedures!FusionTypeID & "_" & rsProcedures!FusionFieldID
    
    DropProcedure sProcedureName
    
    strSPCode = "/* ---------------------------------------------------------------- */" & vbNewLine _
            & "/* Fusion module stored procedure.          */" & vbNewLine _
            & "/* Automatically generated by the System manager.   */" & vbNewLine _
            & "/* ---------------------------------------------------------------- */" & vbNewLine _
            & "CREATE PROCEDURE dbo." & sProcedureName & vbNewLine _
            & "(    @inputValue varchar(255)," & vbNewLine _
            & "     @result varchar(255) OUTPUT)" & vbNewLine _
            & "AS" & vbNewLine _
            & "BEGIN" & vbNewLine & vbNewLine _

    sSQL = "SELECT * FROM tmpFusionFieldMappings WHERE FieldID = " & rsProcedures!FusionFieldID _
            & " AND FusionID = " & rsProcedures!FusionTypeID
    Set rsMapData = daoDb.OpenRecordset(sSQL, dbOpenForwardOnly, dbReadOnly)

    strSPCode = strSPCode & Space$(4) & "SET @result = @inputValue" & vbNewLine

    Do While Not rsMapData.EOF
      strSPCode = strSPCode & Space$(4) & "IF @inputValue = '" & rsMapData!HRProValue & "' SET @result = '" & rsMapData!FusionValue & "'" & vbNewLine
      rsMapData.MoveNext
    Loop

    strSPCode = strSPCode & "END"
  
    gADOCon.Execute strSPCode, , adCmdText + adExecuteNoRecords
    
    rsProcedures.MoveNext
  Loop

  rsProcedures.Close

TidyUpAndExit:
  Set rsProcedures = Nothing
  Set rsMapData = Nothing
  CreateFusionExpressionSPs = bOK
  Exit Function

ErrorTrap:
  OutputError "Error creating Fusion expression stored procedures"
  bOK = False
  Resume TidyUpAndExit

End Function

' Creates the triggers on the transfer table
Public Function CreateFusionTransferTriggers(pfRefreshDatabase As Boolean) As Boolean

  On Error GoTo ErrorTrap

  Dim rsFusionDetails As DAO.Recordset
  Dim strUpdateTrigger As String
  Dim strDeleteTrigger As String
  Dim strDropTrigger As String
  Dim bOK As Boolean
  Dim sSQL As String
  
  bOK = True
   
  ' Drop existing trigger (Insert)
  strDropTrigger = "IF EXISTS" & _
    " (SELECT Name" & _
    "   FROM sysobjects" & _
    "   WHERE id = object_id('[INS_ASRSysFusionTransactions]')" & _
    "     AND objectproperty(id, N'IsTrigger') = 1)" & _
    " DROP TRIGGER [INS_ASRSysFusionTransactions]"
  gADOCon.Execute strDropTrigger, , adCmdText + adExecuteNoRecords
  
  ' Drop existing trigger (Update)
  strDropTrigger = "IF EXISTS" & _
    " (SELECT Name" & _
    "   FROM sysobjects" & _
    "   WHERE id = object_id('[UPD_ASRSysFusionTransactions]')" & _
    "     AND objectproperty(id, N'IsTrigger') = 1)" & _
    " DROP TRIGGER [UPD_ASRSysFusionTransactions]"
  gADOCon.Execute strDropTrigger, , adCmdText + adExecuteNoRecords
  
  ' Drop existing trigger (Delete)
  strDropTrigger = "IF EXISTS" & _
    " (SELECT Name" & _
    "   FROM sysobjects" & _
    "   WHERE id = object_id('[DEL_ASRSysFusionTransactions]')" & _
    "     AND objectproperty(id, N'IsTrigger') = 1)" & _
    " DROP TRIGGER [DEL_ASRSysFusionTransactions]"
  gADOCon.Execute strDropTrigger, , adCmdText + adExecuteNoRecords
  
  ' New triggers
  strUpdateTrigger = vbNullString
  strDeleteTrigger = vbNullString
  
  sSQL = "SELECT c.TableID, MIN(c.ColumnID) AS ColumnID, t.FusionTypeID, t.ASRBaseTableID FROM tmpColumns c" _
    & " INNER JOIN tmpFusionTypes t ON t.ASRBaseTableID = c.TableID" _
    & " WHERE ColumnName NOT IN ('Timestamp', 'ID')" _
    & " GROUP BY c.TableID, t.FusionTypeID, t.ASRBaseTableID"
  Set rsFusionDetails = daoDb.OpenRecordset(sSQL, dbOpenForwardOnly, dbReadOnly)
  
  With rsFusionDetails
    Do While Not .EOF
      strUpdateTrigger = strUpdateTrigger _
        & Space$(8) & "IF @iTransferType = " & Trim(Str(!FusionTypeID)) & " UPDATE " _
        & GetTableName(!ASRBaseTableID) & " SET " _
        & GetColumnName(!ColumnID, False) & " =  " & GetColumnName(!ColumnID, False) & " WHERE ID = @recordID" & vbNewLine
      .MoveNext
    Loop
    .Close
  End With
  
  If LenB(strUpdateTrigger) <> 0 Then
    strUpdateTrigger = "/* ---------------------------------------------------------------- */" & vbNewLine _
        & "/* Fusion module trigger.                   */" & vbNewLine _
        & "/* Automatically generated by the System manager.   */" & vbNewLine _
        & "/* ---------------------------------------------------------------- */" & vbNewLine _
        & "CREATE TRIGGER UPD_ASRSysFusionTransactions ON dbo.ASRSysFusionTransactions" & vbNewLine _
        & "FOR UPDATE" & vbNewLine _
        & "AS" & vbNewLine _
        & "BEGIN" & vbNewLine _
        & Space$(4) & "DECLARE @recordID int," & vbNewLine _
        & Space$(8) & "@iTransferType int," & vbNewLine _
        & Space$(8) & "@iStatus int," & vbNewLine _
        & Space$(8) & "@cursInsertedRecords cursor" & vbNewLine _
        & Space$(4) & "SET @cursInsertedRecords = CURSOR LOCAL FAST_FORWARD FOR SELECT inserted.HRProRecordID, inserted.TransferType, inserted.Status FROM inserted" & vbNewLine _
        & Space$(8) & "LEFT OUTER JOIN deleted ON inserted.TransactionID = deleted.TransactionID" & vbNewLine _
        & Space$(8) & "WHERE Deleted.Status <> inserted.Status AND inserted.Status IN (22,23)" & vbNewLine _
        & Space$(4) & "OPEN @cursInsertedRecords" & vbNewLine _
        & Space$(4) & "FETCH NEXT FROM @cursInsertedRecords INTO @recordID, @iTransferType, @iStatus" & vbNewLine _
        & Space$(4) & "WHILE (@@fetch_status = 0)" & vbNewLine _
        & Space$(4) & "BEGIN" & vbNewLine & strUpdateTrigger & vbNewLine _
        & Space$(8) & "FETCH NEXT FROM @cursInsertedRecords INTO @recordID, @iTransferType, @iStatus" & vbNewLine _
        & Space$(4) & "END" & vbNewLine _
        & "    CLOSE @cursInsertedRecords" & vbNewLine _
        & "    DEALLOCATE @cursInsertedRecords" & vbNewLine & vbNewLine
        
      strUpdateTrigger = strUpdateTrigger _
        & "    IF @@nestLevel = 1 EXECUTE dbo.spASRFusionPurgeTemp 1,0" & vbNewLine & vbNewLine _
        & "    -- Clear the old data for new transactions" & vbNewLine _
        & "    DECLARE @ids TABLE(id integer);" & vbNewLine _
        & "    INSERT @ids" & vbNewLine _
        & "        SELECT [transactionid] FROM inserted" & vbNewLine _
        & "        WHERE [TransactionType] = 0;" & vbNewLine & vbNewLine _
        & "    UPDATE dbo.[ASRSysFusionTransactionData] SET [olddata] = ''" & vbNewLine _
        & "        WHERE [transactionid] IN (SELECT id FROM @ids);" & vbNewLine _
        & "END"
    
    gADOCon.Execute strUpdateTrigger, , adCmdText + adExecuteNoRecords
  End If
  
  
  strDeleteTrigger = "/* ---------------------------------------------------------------- */" & vbNewLine _
            & "/* Fusion module trigger.                   */" & vbNewLine _
            & "/* Automatically generated by the System manager.   */" & vbNewLine _
            & "/* ---------------------------------------------------------------- */" & vbNewLine _
            & "CREATE TRIGGER DEL_ASRSysFusionTransactions ON dbo.ASRSysFusionTransactions" & vbNewLine _
            & "FOR DELETE" & vbNewLine _
            & "AS" & vbNewLine _
            & "BEGIN" & vbNewLine _
             & "   DELETE FROM ASRSysFusionTransactionData WHERE ASRSysFusionTransactionData.TransactionID IN (SELECT TransactionID FROM deleted)" & vbNewLine _
             & "   DELETE FROM ASRSysFusionTransactionWarnings WHERE ASRSysFusionTransactionWarnings.TransactionID IN (SELECT TransactionID FROM deleted)" & vbNewLine _
            & "END"
  gADOCon.Execute strDeleteTrigger, , adCmdText + adExecuteNoRecords

TidyUpAndExit:
  CreateFusionTransferTriggers = bOK
  Exit Function

ErrorTrap:
  OutputError "Error creating Fusion transfer triggers"
  bOK = False
  Resume TidyUpAndExit

End Function


Public Function CreateFusionTransferSPs(pfRefreshDatabase As Boolean) As Boolean
  
  ' Create the Fusion record export stored procedures.
  On Error GoTo ErrorTrap
  
  Dim bOK As Boolean
  Dim sSQL As String

  bOK = True

  DropProcedure "spASRFusionRunManualExport"

TidyUpAndExit:
  CreateFusionTransferSPs = bOK
  Exit Function

ErrorTrap:
  OutputError "Error creating Fusion stored procedures"
  bOK = False
  Resume TidyUpAndExit

End Function



