//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fusion.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fusion.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenHR Fusion Configuration.
        /// </summary>
        internal static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Configuration_32 {
            get {
                object obj = ResourceManager.GetObject("Configuration_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system could not log you on. Make sure your details are correct, then retype your password..
        /// </summary>
        internal static string Database_CantConnect {
            get {
                return ResourceManager.GetString("Database_CantConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is currently locked..
        /// </summary>
        internal static string Database_Lock_CantTakeReadWrite {
            get {
                return ResourceManager.GetString("Database_Lock_CantTakeReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Making changes to the database will affect users who are currently logged into the system.
        ///
        ///You will need to ensure that all users are logged out and that you have locked the system before you can apply these changes..
        /// </summary>
        internal static string Database_Lock_CantTakeSaving {
            get {
                return ResourceManager.GetString("Database_Lock_CantTakeSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User must be a database administrator to run this application.
        /// </summary>
        internal static string Database_NotAdmin {
            get {
                return ResourceManager.GetString("Database_NotAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel files (*.xls)|*.xls|All files (*.*)|*.*.
        /// </summary>
        internal static string Excel_Filter {
            get {
                return ResourceManager.GetString("Excel_Filter", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Log_32 {
            get {
                object obj = ResourceManager.GetObject("Log_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the missing information and try again..
        /// </summary>
        internal static string LoginForm_ValidationFailed {
            get {
                return ResourceManager.GetString("LoginForm_ValidationFailed", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Message_32 {
            get {
                object obj = ResourceManager.GetObject("Message_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column mappings for this category will be lost if you continue..
        /// </summary>
        internal static string MessageBox_ColumnMappingsLost {
            get {
                return ResourceManager.GetString("MessageBox_ColumnMappingsLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file being exported to may be open in another application.
        ///
        ///Please close the application and try again..
        /// </summary>
        internal static string MessageBox_FileLocked {
            get {
                return ResourceManager.GetString("MessageBox_FileLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to purge the log?.
        /// </summary>
        internal static string MessageBox_PurgeLogs {
            get {
                return ResourceManager.GetString("MessageBox_PurgeLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save changes?.
        /// </summary>
        internal static string MessageBox_SaveChanges {
            get {
                return ResourceManager.GetString("MessageBox_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OpenHR Fusion Configuration.
        /// </summary>
        internal static string MessageBox_Title {
            get {
                return ResourceManager.GetString("MessageBox_Title", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Save_32 {
            get {
                object obj = ResourceManager.GetObject("Save_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timed out trying to perform the service action..
        /// </summary>
        internal static string Service_Timeout {
            get {
                return ResourceManager.GetString("Service_Timeout", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Splash {
            get {
                object obj = ResourceManager.GetObject("Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_32 {
            get {
                object obj = ResourceManager.GetObject("Start_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_32 {
            get {
                object obj = ResourceManager.GetObject("Stop_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
