//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://advancedcomputersoftware.com/xml/fusion")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://advancedcomputersoftware.com/xml/fusion", IsNullable=false)]
public partial class serviceUserChange {
    
    private string serviceUserRefField;
    
    private serviceUserChangeServiceUser[] serviceUserDetailsField;
    
    /// <remarks/>
    public string serviceUserRef {
        get {
            return this.serviceUserRefField;
        }
        set {
            this.serviceUserRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("serviceUser", IsNullable=false)]
    public serviceUserChangeServiceUser[] serviceUserDetails {
        get {
            return this.serviceUserDetailsField;
        }
        set {
            this.serviceUserDetailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://advancedcomputersoftware.com/xml/fusion")]
public partial class serviceUserChangeServiceUser {
    
    private string serviceUserIdField;
    
    private string titleField;
    
    private string forenamesField;
    
    private string surnameField;
    
    private System.DateTime dOBField;
    
    private serviceUserChangeServiceUserGender genderField;
    
    private string primarySiteField;
    
    private string roomField;
    
    private System.DateTime admissionDateField;
    
    private bool admissionDateFieldSpecified;
    
    private System.DateTime dischargeDateField;
    
    private bool dischargeDateFieldSpecified;
    
    private string serviceTypeField;
    
    private string fundingTypeField;
    
    private string locationWithinFacilityField;
    
    private System.DateTime validFromField;
    
    private bool validFromFieldSpecified;
    
    private System.DateTime validToField;
    
    private bool validToFieldSpecified;
    
    /// <remarks/>
    public string serviceUserId {
        get {
            return this.serviceUserIdField;
        }
        set {
            this.serviceUserIdField = value;
        }
    }
    
    /// <remarks/>
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
    
    /// <remarks/>
    public string forenames {
        get {
            return this.forenamesField;
        }
        set {
            this.forenamesField = value;
        }
    }
    
    /// <remarks/>
    public string surname {
        get {
            return this.surnameField;
        }
        set {
            this.surnameField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DOB {
        get {
            return this.dOBField;
        }
        set {
            this.dOBField = value;
        }
    }
    
    /// <remarks/>
    public serviceUserChangeServiceUserGender gender {
        get {
            return this.genderField;
        }
        set {
            this.genderField = value;
        }
    }
    
    /// <remarks/>
    public string primarySite {
        get {
            return this.primarySiteField;
        }
        set {
            this.primarySiteField = value;
        }
    }
    
    /// <remarks/>
    public string room {
        get {
            return this.roomField;
        }
        set {
            this.roomField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime admissionDate {
        get {
            return this.admissionDateField;
        }
        set {
            this.admissionDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool admissionDateSpecified {
        get {
            return this.admissionDateFieldSpecified;
        }
        set {
            this.admissionDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime dischargeDate {
        get {
            return this.dischargeDateField;
        }
        set {
            this.dischargeDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool dischargeDateSpecified {
        get {
            return this.dischargeDateFieldSpecified;
        }
        set {
            this.dischargeDateFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string serviceType {
        get {
            return this.serviceTypeField;
        }
        set {
            this.serviceTypeField = value;
        }
    }
    
    /// <remarks/>
    public string fundingType {
        get {
            return this.fundingTypeField;
        }
        set {
            this.fundingTypeField = value;
        }
    }
    
    /// <remarks/>
    public string locationWithinFacility {
        get {
            return this.locationWithinFacilityField;
        }
        set {
            this.locationWithinFacilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime validFrom {
        get {
            return this.validFromField;
        }
        set {
            this.validFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validFromSpecified {
        get {
            return this.validFromFieldSpecified;
        }
        set {
            this.validFromFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public System.DateTime validTo {
        get {
            return this.validToField;
        }
        set {
            this.validToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool validToSpecified {
        get {
            return this.validToFieldSpecified;
        }
        set {
            this.validToFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://advancedcomputersoftware.com/xml/fusion")]
public enum serviceUserChangeServiceUserGender {
    
    /// <remarks/>
    Male,
    
    /// <remarks/>
    Female,
}
