CREATE TABLE [dbo].[ASRSysOvernightProgress](
	[TableName] [varchar](255) NULL,
	[RecCount] [int] NULL,
	[IDRange] [varchar](255) NULL,
	[StartDate] [datetime] NULL,
	[EndDate] [datetime] NULL,
	[DurationMins] [int] NULL, 
    [DurationSecs] INT NULL
) ON [PRIMARY]