CREATE TABLE [dbo].[ASRSysExprComponents](
	[ComponentID] [int] NOT NULL,
	[ExprID] [int] NOT NULL,
	[Type] [smallint] NOT NULL,
	[FieldTableID] [int] NULL,
	[FieldColumnID] [int] NULL,
	[FieldPassBy] [int] NULL,
	[FieldSelectionTableID] [int] NULL,
	[FieldSelectionRecord] [smallint] NULL,
	[FieldSelectionLine] [int] NULL,
	[FieldSelectionOrderID] [int] NULL,
	[FieldSelectionFilter] [int] NULL,
	[FunctionID] [int] NULL,
	[CalculationID] [int] NULL,
	[OperatorID] [int] NULL,
	[ValueType] [int] NULL,
	[ValueCharacter] [varchar](max) NULL,
	[ValueNumeric] [float] NULL,
	[ValueLogic] [bit] NOT NULL,
	[ValueDate] [datetime] NULL,
	[PromptDescription] [varchar](255) NULL,
	[PromptMask] [varchar](255) NULL,
	[PromptSize] [smallint] NULL,
	[PromptDecimals] [smallint] NULL,
	[FunctionReturnType] [smallint] NULL,
	[LookupTableID] [int] NULL,
	[LookupColumnID] [int] NULL,
	[FilterID] [int] NULL,
	[ExpandedNode] [bit] NULL,
	[PromptDateType] [int] NULL,
	[WorkflowElement] [varchar](200) NULL,
	[WorkflowItem] [varchar](200) NULL,
	[WorkflowRecord] [int] NULL,
	[WorkflowRecordTableID] [int] NULL,
	[WorkflowElementProperty] [int] NULL,
 CONSTRAINT [PK_ComponentID] PRIMARY KEY NONCLUSTERED 
(
	[ComponentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]