CREATE TABLE [dbo].[ASRSysWorkflowInstanceValues](
	[InstanceID] [int] NOT NULL,
	[ElementID] [int] NOT NULL,
	[Identifier] [varchar](200) NOT NULL,
	[Value] [varchar](max) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ValueDescription] [varchar](max) NULL,
	[ColumnID] [int] NULL,
	[parent1TableID] [int] NULL,
	[parent1RecordID] [int] NULL,
	[parent2TableID] [int] NULL,
	[parent2RecordID] [int] NULL,
	[EmailID] [int] NULL,
	[TempValue] [varchar](max) NULL,
	[TempParent1TableID] [int] NULL,
	[TempParent1RecordID] [int] NULL,
	[TempParent2TableID] [int] NULL,
	[TempParent2RecordID] [int] NULL,
	[FileUpload_File] [varbinary](max) NULL,
	[FileUpload_ContentType] [varchar](max) NULL,
	[FileUpload_FileName] [varchar](max) NULL,
	[TempFileUpload_File] [varbinary](max) NULL,
	[TempFileUpload_ContentType] [varchar](max) NULL,
	[TempFileUpload_FileName] [varchar](max) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]