CREATE TABLE [dbo].[ASRSysLabelTypes](
	[LabelTypeID] [int] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](25) NOT NULL,
	[LabelHeight] [float] NOT NULL,
	[LabelWidth] [float] NOT NULL,
	[TopMargin] [float] NOT NULL,
	[SideMargin] [float] NOT NULL,
	[VerticalPitch] [float] NOT NULL,
	[HorizontalPitch] [float] NOT NULL,
	[NumberAcross] [int] NOT NULL,
	[NumberDown] [int] NOT NULL,
	[ASRDefined] [bit] NOT NULL,
	[LabelSupplier] [varchar](25) NULL,
	[Name] [varchar](50) NOT NULL,
	[Description] [varchar](255) NOT NULL,
	[Access] [varchar](2) NOT NULL,
	[Username] [varchar](50) NOT NULL,
	[Timestamp] [timestamp] NOT NULL,
	[PageOrientation] [bit] NOT NULL,
	[PageWidth] [float] NOT NULL,
	[PageHeight] [float] NOT NULL,
	[PageTypeID] [int] NOT NULL,
	[IsEnvelope] [bit] NULL,
	[MeasurementMethod] [int] NULL,
	[FromTop] [float] NULL,
	[FromLeft] [float] NULL,
	[FromTopAuto] [bit] NULL,
	[FromLeftAuto] [bit] NULL,
	[HeadingFontName] [varchar](255) NULL,
	[HeadingFontSize] [int] NULL,
	[HeadingFontColour] [float] NULL,
	[HeadingFontBold] [bit] NULL,
	[HeadingFontItalic] [bit] NULL,
	[HeadingFontUnderline] [bit] NULL,
	[StandardFontName] [varchar](255) NULL,
	[StandardFontSize] [int] NULL,
	[StandardFontColour] [float] NULL,
	[StandardFontBold] [bit] NULL,
	[StandardFontItalic] [bit] NULL,
	[StandardFontUnderline] [bit] NULL
) ON [PRIMARY]