CREATE TABLE [dbo].[ASRSysCrossTab](
	[CrossTabID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](255) NULL,
	[TableID] [int] NOT NULL,
	[Selection] [int] NOT NULL,
	[PicklistID] [int] NULL,
	[FilterID] [int] NULL,
	[HorizontalColID] [int] NOT NULL,
	[HorizontalStart] [varchar](20) NULL,
	[HorizontalStop] [varchar](20) NULL,
	[HorizontalStep] [varchar](20) NULL,
	[VerticalColID] [int] NOT NULL,
	[VerticalStart] [varchar](20) NULL,
	[VerticalStop] [varchar](20) NULL,
	[VerticalStep] [varchar](20) NULL,
	[PageBreakColID] [int] NULL,
	[PageBreakStart] [varchar](20) NULL,
	[PageBreakStop] [varchar](20) NULL,
	[PageBreakStep] [varchar](20) NULL,
	[IntersectionType] [int] NULL,
	[IntersectionColID] [int] NULL,
	[Percentage] [bit] NOT NULL,
	[SuppressZeros] [bit] NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[PercentageofPage] [bit] NOT NULL,
	[TimeStamp] [timestamp] NULL,
	[Name] [varchar](50) NOT NULL,
	[PrintFilterHeader] [bit] NULL,
	[OutputPreview] [bit] NULL,
	[OutputFormat] [int] NULL,
	[OutputScreen] [bit] NULL,
	[OutputPrinter] [bit] NULL,
	[OutputPrinterName] [varchar](255) NULL,
	[OutputSave] [bit] NULL,
	[OutputSaveExisting] [int] NULL,
	[OutputEmail] [bit] NULL,
	[OutputEmailAddr] [int] NULL,
	[OutputEmailSubject] [varchar](255) NULL,
	[OutputFilename] [varchar](255) NULL,
	[ThousandSeparators] [bit] NULL,
	[OutputEmailAttachAs] [varchar](255) NULL,
	[CrossTabType] [tinyint] NULL,
	[XAxisLabel] [varchar](255) NULL,
	[XAxisSubLabel1] [varchar](255) NULL,
	[XAxisSubLabel2] [varchar](255) NULL,
	[XAxisSubLabel3] [varchar](255) NULL,
	[YAxisLabel] [varchar](255) NULL,
	[YAxisSubLabel1] [varchar](255) NULL,
	[YAxisSubLabel2] [varchar](255) NULL,
	[YAxisSubLabel3] [varchar](255) NULL,
	[Description1] [varchar](255) NULL,
	[ColorDesc1] [varchar](6) NULL,
	[Description2] [varchar](255) NULL,
	[ColorDesc2] [varchar](6) NULL,
	[Description3] [varchar](255) NULL,
	[ColorDesc3] [varchar](6) NULL,
	[Description4] [varchar](255) NULL,
	[ColorDesc4] [varchar](6) NULL,
	[Description5] [varchar](255) NULL,
	[ColorDesc5] [varchar](6) NULL,
	[Description6] [varchar](255) NULL,
	[ColorDesc6] [varchar](6) NULL,
	[Description7] [varchar](255) NULL,
	[ColorDesc7] [varchar](6) NULL,
	[Description8] [varchar](255) NULL,
	[ColorDesc8] [varchar](6) NULL,
	[Description9] [varchar](255) NULL,
	[ColorDesc9] [varchar](6) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASRSysCrossTab] ADD DEFAULT ('') FOR [Name]