CREATE TABLE [dbo].[ASRSysCrossTab](
	[CrossTabID] [int] IDENTITY(1,1) NOT NULL,
	[Description] [varchar](255) NULL,
	[TableID] [int] NOT NULL,
	[Selection] [int] NOT NULL,
	[PicklistID] [int] NULL,
	[FilterID] [int] NULL,
	[HorizontalColID] [int] NOT NULL,
	[HorizontalStart] [varchar](20) NULL,
	[HorizontalStop] [varchar](20) NULL,
	[HorizontalStep] [varchar](20) NULL,
	[VerticalColID] [int] NOT NULL,
	[VerticalStart] [varchar](20) NULL,
	[VerticalStop] [varchar](20) NULL,
	[VerticalStep] [varchar](20) NULL,
	[PageBreakColID] [int] NULL,
	[PageBreakStart] [varchar](20) NULL,
	[PageBreakStop] [varchar](20) NULL,
	[PageBreakStep] [varchar](20) NULL,
	[IntersectionType] [int] NULL,
	[IntersectionColID] [int] NULL,
	[Percentage] [bit] NOT NULL,
	[SuppressZeros] [bit] NOT NULL,
	[UserName] [varchar](50) NOT NULL,
	[PercentageofPage] [bit] NOT NULL,
	[TimeStamp] [timestamp] NULL,
	[Name] [varchar](50) NOT NULL,
	[PrintFilterHeader] [bit] NULL,
	[OutputPreview] [bit] NULL,
	[OutputFormat] [int] NULL,
	[OutputScreen] [bit] NULL,
	[OutputPrinter] [bit] NULL,
	[OutputPrinterName] [varchar](255) NULL,
	[OutputSave] [bit] NULL,
	[OutputSaveExisting] [int] NULL,
	[OutputEmail] [bit] NULL,
	[OutputEmailAddr] [int] NULL,
	[OutputEmailSubject] [varchar](255) NULL,
	[OutputFilename] [varchar](255) NULL,
	[ThousandSeparators] [bit] NULL,
	[OutputEmailAttachAs] [varchar](255) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[ASRSysCrossTab] ADD  DEFAULT ('') FOR [Name]