CREATE TABLE [dbo].[ASRSysSSIntranetLinks](
	[linkType] [int] NULL,
	[linkOrder] [int] NULL,
	[prompt] [varchar](100) NULL,
	[text] [varchar](100) NULL,
	[screenID] [int] NULL,
	[pageTitle] [varchar](100) NULL,
	[url] [varchar](500) NULL,
	[startMode] [int] NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
	[utilityType] [int] NULL,
	[utilityID] [int] NULL,
	[viewID] [int] NULL,
	[newWindow] [bit] NULL,
	[TableID] [int] NULL,
	[EMailAddress] [varchar](500) NULL,
	[EMailSubject] [varchar](500) NULL,
	[AppFilePath] [varchar](255) NULL,
	[AppParameters] [varchar](255) NULL,
	[DocumentFilePath] [varchar](255) NULL,
	[DisplayDocumentHyperlink] [bit] NULL,
	[SeparatorOrientation] [int] NULL,
	[PictureID] [int] NULL,
	[Chart_Type] [int] NULL,
	[Chart_ShowLegend] [bit] NULL,
	[Chart_ShowGrid] [bit] NULL,
	[Chart_StackSeries] [bit] NULL,
	[Chart_ShowValues] [bit] NULL,
	[Chart_viewID] [int] NULL,
	[Chart_TableID] [int] NULL,
	[Chart_ColumnID] [int] NULL,
	[Chart_FilterID] [int] NULL,
	[Chart_AggregateType] [int] NULL,
	[Element_Type] [int] NULL,
	[UseFormatting] [bit] NULL,
	[Formatting_DecimalPlaces] [int] NULL,
	[Formatting_Use1000Separator] [bit] NULL,
	[Formatting_Prefix] [varchar](max) NULL,
	[Formatting_Suffix] [varchar](max) NULL,
	[UseConditionalFormatting] [bit] NULL,
	[ConditionalFormatting_Operator_1] [varchar](max) NULL,
	[ConditionalFormatting_Value_1] [varchar](max) NULL,
	[ConditionalFormatting_Style_1] [varchar](max) NULL,
	[ConditionalFormatting_Colour_1] [varchar](max) NULL,
	[ConditionalFormatting_Operator_2] [varchar](max) NULL,
	[ConditionalFormatting_Value_2] [varchar](max) NULL,
	[ConditionalFormatting_Style_2] [varchar](max) NULL,
	[ConditionalFormatting_Colour_2] [varchar](max) NULL,
	[ConditionalFormatting_Operator_3] [varchar](max) NULL,
	[ConditionalFormatting_Value_3] [varchar](max) NULL,
	[ConditionalFormatting_Style_3] [varchar](max) NULL,
	[ConditionalFormatting_Colour_3] [varchar](max) NULL,
	[SeparatorColour] [varchar](max) NULL,
	[InitialDisplayMode] [int] NULL,
	[Chart_TableID_2] [int] NULL,
	[Chart_ColumnID_2] [int] NULL,
	[Chart_TableID_3] [int] NULL,
	[Chart_ColumnID_3] [int] NULL,
	[Chart_SortOrderID] [int] NULL,
	[Chart_SortDirection] [int] NULL,
	[Chart_ColourID] [int] NULL,
	[Chart_ShowPercentages] [bit] NULL,
 CONSTRAINT [PK_ASRSysSSIntranetLinks] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]