CREATE TABLE [dbo].[ASRSysControls](
	[ScreenID] [int] NOT NULL,
	[PageNo] [smallint] NOT NULL,
	[ControlLevel] [smallint] NOT NULL,
	[TableID] [int] NULL,
	[ColumnID] [int] NULL,
	[ControlType] [int] NULL,
	[ControlIndex] [smallint] NOT NULL,
	[TopCoord] [int] NOT NULL,
	[LeftCoord] [int] NOT NULL,
	[Height] [int] NULL,
	[Width] [int] NOT NULL,
	[Caption] [varchar](max) NULL,
	[BackColor] [int] NULL,
	[ForeColor] [int] NULL,
	[FontName] [varchar](50) NULL,
	[FontSize] [smallint] NULL,
	[FontBold] [bit] NOT NULL,
	[FontItalic] [bit] NOT NULL,
	[FontStrikeThru] [bit] NOT NULL,
	[FontUnderline] [bit] NOT NULL,
	[PictureID] [int] NULL,
	[DisplayType] [smallint] NULL,
	[ContainerType] [smallint] NULL,
	[ContainerIndex] [smallint] NULL,
	[TabIndex] [smallint] NULL,
	[BorderStyle] [smallint] NULL,
	[Alignment] [smallint] NULL,
	[ReadOnly] [bit] NULL,
	[NavigateTo] [nvarchar](max) NULL,
	[NavigateIn] [tinyint] NULL,
	[NavigateOnSave] [bit] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]