//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHRTestToLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRSysWorkflowElementColumn
    {
        public int ID { get; set; }
        public int ElementID { get; set; }
        public int ColumnID { get; set; }
        public int ValueType { get; set; }
        public string Value { get; set; }
        public string WFFormIdentifier { get; set; }
        public string WFValueIDentifier { get; set; }
        public Nullable<int> DBColumnID { get; set; }
        public Nullable<int> DBRecord { get; set; }
        public Nullable<int> CalcID { get; set; }
    }
}
