//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHR.TestToLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRSysExpression
    {
        public int ExprID { get; set; }
        public string Name { get; set; }
        public int ReturnType { get; set; }
        public int ReturnSize { get; set; }
        public int ReturnDecimals { get; set; }
        public int Type { get; set; }
        public Nullable<int> ParentComponentID { get; set; }
        public string Description { get; set; }
        public byte[] Timestamp { get; set; }
        public int TableID { get; set; }
        public string Username { get; set; }
        public string Access { get; set; }
        public Nullable<bool> ExpandedNode { get; set; }
        public Nullable<bool> ViewInColour { get; set; }
        public Nullable<int> UtilityID { get; set; }
    }
}
