//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHR.TestToLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRSysWorkflowElementItem
    {
        public int ID { get; set; }
        public int ElementID { get; set; }
        public string Caption { get; set; }
        public Nullable<int> DBColumnID { get; set; }
        public Nullable<int> DBRecord { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> InputType { get; set; }
        public Nullable<int> InputSize { get; set; }
        public Nullable<int> InputDecimals { get; set; }
        public string InputDefault { get; set; }
        public string WFFormIdentifier { get; set; }
        public string WFValueIdentifier { get; set; }
        public int ItemType { get; set; }
        public Nullable<int> LeftCoord { get; set; }
        public Nullable<int> TopCoord { get; set; }
        public Nullable<int> Width { get; set; }
        public Nullable<int> Height { get; set; }
        public Nullable<int> BackColor { get; set; }
        public Nullable<int> ForeColor { get; set; }
        public Nullable<int> PictureID { get; set; }
        public Nullable<bool> PictureBorder { get; set; }
        public string FontName { get; set; }
        public Nullable<short> FontSize { get; set; }
        public Nullable<bool> FontBold { get; set; }
        public Nullable<bool> FontItalic { get; set; }
        public Nullable<bool> FontStrikeThru { get; set; }
        public Nullable<bool> FontUnderline { get; set; }
        public Nullable<short> Alignment { get; set; }
        public Nullable<short> ZOrder { get; set; }
        public Nullable<short> TabIndex { get; set; }
        public Nullable<short> BackStyle { get; set; }
        public Nullable<int> BackColorEven { get; set; }
        public Nullable<int> BackColorOdd { get; set; }
        public Nullable<bool> ColumnHeaders { get; set; }
        public Nullable<int> ForeColorEven { get; set; }
        public Nullable<int> ForeColorOdd { get; set; }
        public Nullable<int> HeaderBackColor { get; set; }
        public string HeadFontName { get; set; }
        public Nullable<short> HeadFontSize { get; set; }
        public Nullable<bool> HeadFontBold { get; set; }
        public Nullable<bool> HeadFontItalic { get; set; }
        public Nullable<bool> HeadFontStrikeThru { get; set; }
        public Nullable<bool> HeadFontUnderline { get; set; }
        public Nullable<int> Headlines { get; set; }
        public Nullable<int> TableID { get; set; }
        public string RecSelWebFormIdentifier { get; set; }
        public string RecSelIdentifier { get; set; }
        public Nullable<int> ForeColorHighlight { get; set; }
        public Nullable<int> BackColorHighlight { get; set; }
        public Nullable<int> LookupTableID { get; set; }
        public Nullable<int> LookupColumnID { get; set; }
        public Nullable<int> RecordTableID { get; set; }
        public Nullable<short> Orientation { get; set; }
        public Nullable<int> RecordOrderID { get; set; }
        public Nullable<int> RecordFilterID { get; set; }
        public Nullable<int> Behaviour { get; set; }
        public Nullable<bool> Mandatory { get; set; }
        public Nullable<int> CalcID { get; set; }
        public Nullable<int> CaptionType { get; set; }
        public Nullable<int> DefaultValueType { get; set; }
        public Nullable<int> VerticalOffset { get; set; }
        public Nullable<int> VerticalOffsetBehaviour { get; set; }
        public Nullable<int> HorizontalOffset { get; set; }
        public Nullable<int> HorizontalOffsetBehaviour { get; set; }
        public Nullable<int> HeightBehaviour { get; set; }
        public Nullable<int> WidthBehaviour { get; set; }
        public Nullable<bool> PasswordType { get; set; }
        public Nullable<int> LookupFilterColumnID { get; set; }
        public Nullable<int> LookupFilterOperator { get; set; }
        public string LookupFilterValue { get; set; }
        public Nullable<int> pageno { get; set; }
        public Nullable<byte> buttonstyle { get; set; }
        public Nullable<int> LookupOrderID { get; set; }
        public string HotSpotIdentifier { get; set; }
        public Nullable<bool> UseAsTargetIdentifier { get; set; }
    }
}
