//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHR.TestToLive
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASRSysWorkflow
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public bool enabled { get; set; }
        public Nullable<short> initiationtype { get; set; }
        public Nullable<int> basetable { get; set; }
        public string querystring { get; set; }
        public Nullable<int> pictureid { get; set; }
        public bool locked { get; set; }
        public Nullable<System.DateTime> lastupdated { get; set; }
        public string lastupdatedby { get; set; }
        public Nullable<bool> HasTargetIdentifier { get; set; }
    }
}
