//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHR.TestToLive
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class npg_openhr8_2Entities : DbContext
    {
        public npg_openhr8_2Entities()
            : base("name=npg_openhr8_2Entities")
        {
        }

        public npg_openhr8_2Entities(string nameOrConnectionString) : base(nameOrConnectionString)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ASRSysExprComponent> ASRSysExprComponents { get; set; }
        public virtual DbSet<ASRSysExpression> ASRSysExpressions { get; set; }
        public virtual DbSet<ASRSysWorkflowElementColumn> ASRSysWorkflowElementColumns { get; set; }
        public virtual DbSet<ASRSysWorkflowElementItem> ASRSysWorkflowElementItems { get; set; }
        public virtual DbSet<ASRSysWorkflowElementItemValue> ASRSysWorkflowElementItemValues { get; set; }
        public virtual DbSet<ASRSysWorkflowElement> ASRSysWorkflowElements { get; set; }
        public virtual DbSet<ASRSysWorkflowElementValidation> ASRSysWorkflowElementValidations { get; set; }
        public virtual DbSet<ASRSysWorkflowLinks> ASRSysWorkflowLinks { get; set; }
        public virtual DbSet<ASRSysWorkflows> ASRSysWorkflows { get; set; }
    }
}
