'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ChangePassword

   '''<summary>
   '''lblWelcome control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblWelcome As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblCurrPassword control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblCurrPassword As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''txtCurrPassword control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtCurrPassword As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''lblNewPassword control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblNewPassword As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''txtNewPassword control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtNewPassword As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''lblConfPassword control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblConfPassword As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''txtConfPassword control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtConfPassword As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnSubmit2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSubmit2 As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnSubmit control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.LinkButton

   '''<summary>
   '''btnCancel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.HyperLink
End Class
