'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Registration

   '''<summary>
   '''lblWelcome control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblWelcome As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''lblEmail control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

   '''<summary>
   '''txtEmail control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

   '''<summary>
   '''btnSubmit2 control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSubmit2 As Global.System.Web.UI.WebControls.Button

   '''<summary>
   '''btnSubmit control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.LinkButton

   '''<summary>
   '''btnCancel control.
   '''</summary>
   '''<remarks>
   '''Auto-generated field.
   '''To modify move field declaration from designer file to code-behind file.
   '''</remarks>
   Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.HyperLink
End Class
