//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenHRNexus.WebAPI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OpenHRNexus.WebAPI.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or you can login using one of the social logins below.
        /// </summary>
        internal static string Label_AlternateLogins {
            get {
                return ResourceManager.GetString("Label_AlternateLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        internal static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Facebook.
        /// </summary>
        internal static string Label_ConnectWithFacebook {
            get {
                return ResourceManager.GetString("Label_ConnectWithFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with Google+.
        /// </summary>
        internal static string Label_ConnectWithGoogle {
            get {
                return ResourceManager.GetString("Label_ConnectWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        internal static string Label_EmailAddress {
            get {
                return ResourceManager.GetString("Label_EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Label_Home {
            get {
                return ResourceManager.GetString("Label_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Label_LoginButton {
            get {
                return ResourceManager.GetString("Label_LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string Label_SignUp {
            get {
                return ResourceManager.GetString("Label_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Social Logins.
        /// </summary>
        internal static string Label_SocialLogins {
            get {
                return ResourceManager.GetString("Label_SocialLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Label_SubmitButton {
            get {
                return ResourceManager.GetString("Label_SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Refresh Tokens.
        /// </summary>
        internal static string Label_UseRefreshTokens {
            get {
                return ResourceManager.GetString("Label_UseRefreshTokens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Label_Username {
            get {
                return ResourceManager.GetString("Label_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have a Username and Password, you can use the button below to access OpenHR Nexus..
        /// </summary>
        internal static string Text_LoginDescription {
            get {
                return ResourceManager.GetString("Text_LoginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the button below to create Username and Password to access OpenHR Nexus..
        /// </summary>
        internal static string Text_SignUpDescription {
            get {
                return ResourceManager.GetString("Text_SignUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome #FullName#, you last logged in on #LastLoginDate#; you Security Group is &quot;#SecurityGroup#&quot;.
        /// </summary>
        internal static string Text_WelcomeMessage {
            get {
                return ResourceManager.GetString("Text_WelcomeMessage", resourceCulture);
            }
        }
    }
}
