-- Generated by the server assembly
CREATE PROCEDURE [dbo].[spASRGetDomainPolicyFromAssembly]
	@lockoutDuration [bigint] OUTPUT,
	@lockoutThreshold [bigint] OUTPUT,
	@lockoutObservationWindow [bigint] OUTPUT,
	@maxPwdAge [bigint] OUTPUT,
	@minPwdAge [bigint] OUTPUT,
	@minPwdLength [bigint] OUTPUT,
	@pwdHistoryLength [bigint] OUTPUT,
	@pwdProperties [bigint] OUTPUT
	AS
		RETURN 0
	