-- Generated by the server assembly
CREATE FUNCTION [dbo].[udfASRNetGetLicenceKey](@inKey [nvarchar](4000), @moduleName [nvarchar](4000))
RETURNS [int] WITH EXECUTE AS CALLER
AS
BEGIN
	RETURN 0
END