-- Generated by the server assembly
CREATE FUNCTION [dbo].[udfASRNetGetWorkflowQueryString](@instanceID [int], @stepID [int], @userPwd [nvarchar](4000), @server [nvarchar](4000), @database [nvarchar](4000))
RETURNS [nvarchar](4000) WITH EXECUTE AS CALLER
AS
BEGIN
	RETURN 0
END