using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OpenHRNexus.Common.Models {
	public class Personnel_Records_Model {
		public Nullable<decimal> Absence_Count_of_SICK_in_Current_Year { get; set; }
		public Nullable<decimal> ABSENCE_FUNCTIONS_COMBINED_will_return_1000 { get; set; }
		public Nullable<System.DateTime> Add_Days_to_Date__hourly_rate_from_01011940 { get; set; }
		public Nullable<System.DateTime> Add_Days_To_Date_using_Unique_Code { get; set; }
		public string Address_1 { get; set; }
		public string Address_1_first_2_characters { get; set; }
		public string Address_2 { get; set; }
		public string Address_3 { get; set; }
		public Nullable<System.DateTime> Advertisement_Date { get; set; }
		public string AFD_Address { get; set; }
		public string AFD_Postcode { get; set; }
		public Nullable<int> Age { get; set; }
		public Nullable<decimal> Annual_Rate { get; set; }
		public string Application_Notes { get; set; }
		public Nullable<bool> AUDIT_FUNCTIONS_COMBINED_WILL_RETURN_TRUE_IF_SURNAME_IS_CHANGED { get; set; }
		public Nullable<bool> AVCs_Paid { get; set; }
		public string Bank_Account_Name { get; set; }
		public string Bank_Account_No { get; set; }
		public string Bank_Address_1 { get; set; }
		public string Bank_Address_2 { get; set; }
		public string Bank_Address_3 { get; set; }
		public string Bank_Address_4 { get; set; }
		public string Bank_Address_Postcode { get; set; }
		public string Bank_Branch { get; set; }
		public string Bank_Name { get; set; }
		public string Bank_Sort_Code { get; set; }
		public string BSociety_Roll_No { get; set; }
		public string Calc_12_Nested_Levels_from_Training_Booking_Top_Line { get; set; }
		public Nullable<decimal> Calc_Default_Staff_No { get; set; }
		public string Calc_of_Address_3 { get; set; }
		public Nullable<System.DateTime> Calc_of_Calendar_Date { get; set; }
		public Nullable<System.DateTime> Calendar_Date_Test { get; set; }
		public string CHARACTER_FUNCTIONS_COMBINED_1 { get; set; }
		public string Character_Numeric { get; set; }
		public byte[] Charting { get; set; }
		public string co_code { get; set; }
		public string co_name { get; set; }
		public string COmb_Functions_calcs_in_calc_SHould_Return_OK { get; set; }
		public string Company_Code { get; set; }
		public string COMPARISON_FUNCTIONS_COMBINED { get; set; }
		public string Conversion_text { get; set; }
		public Nullable<bool> convert_currency { get; set; }
		public Nullable<decimal> Convert_Currency_divide_by_0 { get; set; }
		public string Cost_Code { get; set; }
		public string County { get; set; }
		public Nullable<decimal> Currency_Conversion_Amount { get; set; }
		public Nullable<decimal> Currency_Conversion_Amount_calculated { get; set; }
		public string Currency_Conversion_From_Country { get; set; }
		public string Currency_Conversion_To_Country { get; set; }
		public Nullable<decimal> Current_Allowance_Total { get; set; }
		public Nullable<decimal> Current_Benefit_Total { get; set; }
		public Nullable<decimal> Current_Deduction_Total { get; set; }
		public Nullable<decimal> Current_Salary { get; set; }
		public Nullable<System.DateTime> Current_Salary_Date { get; set; }
		public Nullable<decimal> Current_Salary_Size_2 { get; set; }
		public string Custom_Trigger_Record_Last_Changed_Date_and_By { get; set; }
		public Nullable<System.DateTime> DATE_FUNCTIONS_COMBINED_1_should_return_system_date_plus_6_days { get; set; }
		public Nullable<System.DateTime> DATE_FUNCTIONS_COMBINED_2_should_return_date_function_1_date_plus_4022_years { get; set; }
		public Nullable<System.DateTime> DATE_FUNCTIONS_COMBINED_3__returns_25122012 { get; set; }
		public string DATE_FUNCTIONS_COMBINED_4_RETURNS_nice_date_25122012 { get; set; }
		public Nullable<System.DateTime> Date_of_Birth { get; set; }
		public Nullable<System.DateTime> Date_of_Last_Eye_Test { get; set; }
		public Nullable<bool> Delete_Record_in_Workflow_Trigger { get; set; }
		public string Department { get; set; }
		public string Department_Division { get; set; }
		public Nullable<bool> Director { get; set; }
		public Nullable<bool> Disabled { get; set; }
		public string Division { get; set; }
		public Nullable<bool> Driving_Licence { get; set; }
		public string EMail_Home { get; set; }
		public string EMail_Work { get; set; }
		public Nullable<bool> Enable_Overnight_Job_triggers_test { get; set; }
		public string Ethnic_Group { get; set; }
		public string Ethnic_Group_Description { get; set; }
		public string Ethnic_Origin { get; set; }
		public Nullable<bool> Ex_Directory { get; set; }
		public string Fax { get; set; }
		public Nullable<bool> Fire_Warden { get; set; }
		public Nullable<System.DateTime> Fire_Warden_Certificate_Date { get; set; }
		public Nullable<System.DateTime> Fire_Warden_Expiry_Date { get; set; }
		public Nullable<System.DateTime> First_Aid_Certificate_Date { get; set; }
		public Nullable<System.DateTime> First_Aid_Expiry_Date { get; set; }
		public Nullable<bool> First_Aider { get; set; }
		public string Forenames { get; set; }
		public string Forenames_and_Surname { get; set; }
		public string Full_Part_Time { get; set; }
		public Nullable<decimal> Function_8_0_Base_Record_ID { get; set; }
		public Nullable<System.DateTime> Function_8_0_Create_Exact_Date_Xmas_Day { get; set; }
		public Nullable<decimal> Function_Absence_Between_2_Dates_Type_HOLS { get; set; }
		public Nullable<decimal> Function_Absence_Duration__type_HOLS { get; set; }
		public Nullable<System.DateTime> Function_Add_Days_To_Date_10 { get; set; }
		public Nullable<System.DateTime> Function_Add_Months_To_Date_1 { get; set; }
		public Nullable<System.DateTime> Function_Add_Years_To_Date_1 { get; set; }
		public Nullable<decimal> Function_Bradford_Factor { get; set; }
		public Nullable<decimal> Function_Bradford_Factor_Current_Year { get; set; }
		public Nullable<decimal> Function_Convert_Character_To_Numeric { get; set; }
		public string Function_Convert_Numeric_To_Character { get; set; }
		public string Function_Convert_To_lowercase { get; set; }
		public string Function_Convert_to_Propercase { get; set; }
		public string Function_Convert_To_UPPER_CASE { get; set; }
		public string Function_Current_User { get; set; }
		public Nullable<int> Function_Day_Of_Date { get; set; }
		public Nullable<decimal> Function_Day_Of_Week { get; set; }
		public Nullable<int> Function_Days_Between_Two_dates { get; set; }
		public byte[] Function_Definition_Information { get; set; }
		public string Function_Extract_Characters_From_Right_4 { get; set; }
		public string Function_Extract_Charcters_From_Left_4 { get; set; }
		public string Function_Extract_Part_OF_a_Character_String_from_2_extract_3 { get; set; }
		public Nullable<bool> Function_Field_Changed_Between_2_Dates_Surname { get; set; }
		public Nullable<System.DateTime> Function_Field_Last_Changed_Date { get; set; }
		public Nullable<System.DateTime> Function_First_Day_Of_Month { get; set; }
		public Nullable<System.DateTime> Function_First_Day_Of_Year { get; set; }
		public string Function_Firstname_From_Forename { get; set; }
		public string Function_Get_Field_From_Database_Record_Manager_Email { get; set; }
		public string Function_If_Then_Else_is_it_Monday { get; set; }
		public string Function_Initials_From_Forenames { get; set; }
		public Nullable<bool> Function_Is_Between_Current_Salary_10000_and_20000 { get; set; }
		public Nullable<bool> Function_Is_Field_Empty_Conversion_text { get; set; }
		public string Function_is_field_empty_or_populated { get; set; }
		public Nullable<bool> Function_is_Field_Empty_with_if_then_else { get; set; }
		public string Function_is_Field_Empty_with_if_then_else_and_is_field_populated_HEADS_TAILS { get; set; }
		public Nullable<bool> Function_Is_Field_Populated_Conversion_text { get; set; }
		public Nullable<bool> Function_Is_Overnight_Process { get; set; }
		public string Function_Is_overnight_Process__Last_Updated_By { get; set; }
		public Nullable<System.DateTime> Function_Is_overnight_Process__Last_Updated_on { get; set; }
		public string Function_Is_valid_character_set_H_save_validation { get; set; }
		public Nullable<bool> Function_IS_valid_charater_set_H { get; set; }
		public Nullable<bool> Function_is_valid_NI_Number_Test_Value { get; set; }
		public Nullable<System.DateTime> Function_Last_Day_Of_Month { get; set; }
		public Nullable<System.DateTime> Function_Last_Day_Of_Year { get; set; }
		public Nullable<decimal> Function_Length_Of_Character_Field { get; set; }
		public Nullable<decimal> Function_Maximum { get; set; }
		public Nullable<decimal> Function_Minimum { get; set; }
		public Nullable<int> Function_Month_Of_Date { get; set; }
		public string Function_Name_Of_Day { get; set; }
		public string Function_Name_Of_Month { get; set; }
		public string Function_Nice_Date { get; set; }
		public string Function_Nice_Time { get; set; }
		public Nullable<decimal> Function_Number_Of_Working_Days_Per_Week { get; set; }
		public string Function_Parentheses { get; set; }
		public Nullable<int> Function_Remaining_Months_Since_Whole_Years { get; set; }
		public string Function_Remove_Leading_and_Trailing_Spaces { get; set; }
		public string Function_Replace_character_string { get; set; }
		public Nullable<System.DateTime> Function_Round_Date_To_Start_Of_Nearest_Month { get; set; }
		public Nullable<decimal> Function_Round_Down_To_Nearest_Whole_Number { get; set; }
		public Nullable<decimal> Function_Round_To_Nearest_Number_0 { get; set; }
		public Nullable<decimal> Function_Round_To_Nearest_Number_5 { get; set; }
		public Nullable<decimal> Function_Round_Up_To_Nearest_Whole_Number { get; set; }
		public Nullable<decimal> Function_Search_For_Character_String_Smith { get; set; }
		public Nullable<decimal> Function_Service_Months { get; set; }
		public Nullable<decimal> Function_Service_Years { get; set; }
		public Nullable<decimal> Function_Statutory_Redundancy_Pay { get; set; }
		public Nullable<System.DateTime> Function_System_Date { get; set; }
		public Nullable<decimal> Function_Unique_Code { get; set; }
		public Nullable<int> Function_WeekDays_Between_Two_Dates { get; set; }
		public Nullable<int> Function_Whole_Months_Between_Two_Dates { get; set; }
		public Nullable<int> Function_Whole_Years_Between_Two_Dates { get; set; }
		public Nullable<int> Function_Whole_Years_Until_Current_Date { get; set; }
		public Nullable<decimal> Function_Working_Days_Between_2_Dates { get; set; }
		public Nullable<decimal> Function_Year_Of_Date { get; set; }
		public string Gender { get; set; }
		public string GENERAL_FUNCTIONS_COMBINED { get; set; }
		public string get_field_to_get_manager_name { get; set; }
		public string Grade { get; set; }
		public Nullable<decimal> Holiday_Balance { get; set; }
		public Nullable<decimal> Holiday_Brought_Forward { get; set; }
		public Nullable<decimal> Holiday_Entitlement { get; set; }
		public Nullable<decimal> Holiday_Taken { get; set; }
		public Nullable<decimal> Horizontal { get; set; }
		public Nullable<decimal> Hourly_Rate { get; set; }
		public string HR_Manager { get; set; }
		public int ID { get; set; }
		public string Initials { get; set; }
		public string Internal_Phone { get; set; }
		public string Intranet_Line_Manager_Login { get; set; }
		public string Intranet_Self_Service_Login { get; set; }
		public string Is_valid_Character_set_H_value { get; set; }
		public byte[] Job_Specification { get; set; }
		public string Job_Title { get; set; }
		public string Known_As { get; set; }
		public string Last_Changed_By { get; set; }
		public Nullable<decimal> Last_Increase_Amount { get; set; }
		public Nullable<decimal> Last_Increase_Pct { get; set; }
		public string Last_Updated_By { get; set; }
		public string Last_Updated_BY__Is_Overnight_Process { get; set; }
		public string Last_Updated_BY_inc_overnight { get; set; }
		public Nullable<System.DateTime> Last_Updated_On { get; set; }
		public Nullable<System.DateTime> Leaving_Date { get; set; }
		public string Leaving_Reason { get; set; }
		public Nullable<decimal> Life_Ins_Annual_Cost { get; set; }
		public string Life_Ins_Cover { get; set; }
		public string Life_Ins_Provider { get; set; }
		public string Life_Ins_Provider_2 { get; set; }
		public string Life_Ins_Scheme_Ref_No { get; set; }
		public string Local_OLE { get; set; }
		public string Lookup_All_Column_Types { get; set; }
		public string Lookup_Two_Columns { get; set; }
		public string lowercase { get; set; }
		public string Manager { get; set; }
		public string Manager_2 { get; set; }
		public Nullable<decimal> Manager_Staff_Number { get; set; }
		public string Marital_Status { get; set; }
		public Nullable<decimal> Max_Unique_Code { get; set; }
		public string Mobile { get; set; }
		public Nullable<bool> Mobile_Workflow_Activated { get; set; }
		public Nullable<decimal> Monthly_Rate { get; set; }
		public string Nationality { get; set; }
		public string Nested_Calc_Multi_Table { get; set; }
		public Nullable<decimal> New_Test_Column_9_Box_CT { get; set; }
		public Nullable<System.DateTime> Next_Appraisal_Due { get; set; }
		public Nullable<System.DateTime> Next_Birthday { get; set; }
		public Nullable<System.DateTime> Next_Discipline_Expiry { get; set; }
		public string NI_Letter { get; set; }
		public string NI_Number { get; set; }
		public string NI_Number_Test_Value { get; set; }
		public string No_is_overnight_Process__Last_Updated_By { get; set; }
		public Nullable<System.DateTime> No_is_overnight_Process__Last_Updated_on { get; set; }
		public string No_trimming { get; set; }
		public string Notes { get; set; }
		public string Notice_In { get; set; }
		public Nullable<int> Notice_Period { get; set; }
		public Nullable<decimal> Numeric_1 { get; set; }
		public Nullable<decimal> Numeric_2 { get; set; }
		public string NUMERIC_FUNCTIONS_COMBINED { get; set; }
		public byte[] OLE_Embedded_Read_Only { get; set; }
		public byte[] OLE_New_Link_or_embedded_100k { get; set; }
		public byte[] OLE_New_Linked { get; set; }
		public string OLE_Old_copied_to_local { get; set; }
		public string OLE_Old_Copied_to_server { get; set; }
		public byte[] OLE_Read_Only { get; set; }
		public Nullable<bool> One_Years_Service_Previous { get; set; }
		public Nullable<decimal> Operator_Divide_By { get; set; }
		public Nullable<bool> Operator_is_contained_within { get; set; }
		public Nullable<bool> Out_Of_Office { get; set; }
		public string Outlook_Calendar_Details { get; set; }
		public string Payment_Frequency { get; set; }
		public string Payment_Method { get; set; }
		public string PAYROLL_CODE { get; set; }
		public Nullable<decimal> Pension_Ees_Amount { get; set; }
		public Nullable<decimal> Pension_Ees_Pct { get; set; }
		public Nullable<System.DateTime> Pension_Eligible { get; set; }
		public Nullable<System.DateTime> Pension_Entry { get; set; }
		public Nullable<decimal> Pension_Ers_Amount { get; set; }
		public Nullable<decimal> Pension_Ers_Pct { get; set; }
		public string Pension_Scheme { get; set; }
		public Nullable<decimal> Percentage_of_Grade { get; set; }
		public Nullable<decimal> PERSONNEL_FUNCTIONS_COMBINED { get; set; }
		public Nullable<decimal> PHI_Annual_Cost { get; set; }
		public string PHI_Provider { get; set; }
		public string PHI_Scheme_Ref_No { get; set; }
		public byte[] PHOTO_ID_BADGE { get; set; }
		public byte[] Photo_Linked_and_embedded { get; set; }
		public byte[] Photo_New_Linked { get; set; }
		public byte[] Photo_new_Linked_or_Embedded_100k { get; set; }
		public string Photo_Old_copied_to_photo { get; set; }
		public string Photograph { get; set; }
		public string Place_of_Birth { get; set; }
		public string Postcode { get; set; }
		public string Previous_Name { get; set; }
		public Nullable<decimal> Previous_Salary { get; set; }
		public Nullable<System.DateTime> Previous_Service_From { get; set; }
		public Nullable<System.DateTime> Previous_Service_To { get; set; }
		public Nullable<System.DateTime> Probation_End { get; set; }
		public string Probation_In { get; set; }
		public Nullable<int> Probation_Period { get; set; }
		public string Propercase { get; set; }
		public Nullable<System.DateTime> Proposed_Increase_Date { get; set; }
		public Nullable<decimal> Proposed_Salary { get; set; }
		public Nullable<bool> Ready_for_Payroll_Transfer { get; set; }
		public Nullable<decimal> Recruitment_Cost { get; set; }
		public Nullable<System.DateTime> Recruitment_Offer_Made { get; set; }
		public string Recruitment_Source { get; set; }
		public Nullable<decimal> Recursive_Trigger_Unique_Code { get; set; }
		public string Regional_ID { get; set; }
		public string Reports_to_Name { get; set; }
		public Nullable<decimal> Reports_to_Staff_No { get; set; }
		public string Reports_to_Surname { get; set; }
		public Nullable<int> Retirement_Age { get; set; }
		public Nullable<System.DateTime> Retirement_Date { get; set; }
		public Nullable<decimal> Salary_Range_From { get; set; }
		public Nullable<decimal> Salary_Range_To { get; set; }
		public Nullable<decimal> Save_Count { get; set; }
		public Nullable<bool> Send_Mail { get; set; }
		public string Send_Mail_Instant_Link { get; set; }
		public string Send_Mail_is_set_to { get; set; }
		public Nullable<System.DateTime> Send_Mail_Offset_Date { get; set; }
		public string Server_OLE { get; set; }
		public Nullable<int> Service_Months { get; set; }
		public Nullable<int> Service_Years { get; set; }
		public string Shift { get; set; }
		public string Special_Requirements { get; set; }
		public Nullable<decimal> SRP_Age_at_Leaving_Date { get; set; }
		public Nullable<int> SSP_QUalifying_Days { get; set; }
		public Nullable<decimal> Staff_Nos_Lookup { get; set; }
		public Nullable<decimal> Staff_Nos_Lookup_Equal_To { get; set; }
		public Nullable<decimal> Staff_Number { get; set; }
		public Nullable<bool> Stakeholder_Pension { get; set; }
		public Nullable<decimal> Standard_Hours { get; set; }
		public Nullable<System.DateTime> Start_Date { get; set; }
		public string Surname { get; set; }
		public string Surname_and_Forename { get; set; }
		public Nullable<System.DateTime> System_Date_Column_plus_1_day { get; set; }
		public string Tax_Code { get; set; }
		public string Telephone { get; set; }
		public Nullable<bool> Temporary_Employee { get; set; }
		public byte[] Terms_and_Conditions { get; set; }
		public string Test_Column_for_CT { get; set; }
		public Nullable<decimal> THOU { get; set; }
		public Nullable<decimal> Thousand_Separator_Lookup { get; set; }
		public string Title { get; set; }
		public Nullable<decimal> Total_Benefit_Cost { get; set; }
		public Nullable<decimal> Total_Outstanding_Loan_Balance { get; set; }
		public Nullable<decimal> Total_Package { get; set; }
		public string Town { get; set; }
		public string Trade_Union { get; set; }
		public Nullable<System.DateTime> Trigger_First_Line_of_Absence_type_of_SICK_order_by_Salary_Date { get; set; }
		public Nullable<decimal> Trigger_First_Line_of_Salary_order_by_Salary_Date { get; set; }
		public Nullable<System.DateTime> Trigger_Last_Line_of_Absence_type_of_SICK_order_by_Salary_Date { get; set; }
		public Nullable<decimal> Trigger_Last_Line_of_Salary_order_by_Salary_Date { get; set; }
		public Nullable<System.DateTime> Trigger_specific_line_2_of_Absence_type_of_SICK_order_by_Salary_Date { get; set; }
		public Nullable<decimal> Trigger_Specific_Line_2_of_Salary_order_by_Salary_Date { get; set; }
		public Nullable<decimal> Unique_Code { get; set; }
		public Nullable<decimal> Unique_Code_calc_only_if_empty { get; set; }
		public string UPPERCASE { get; set; }
		public Nullable<int> Vertical { get; set; }
		public string Web_Form_Input_Test_8_characters { get; set; }
		public Nullable<bool> Week1_Month1 { get; set; }
		public Nullable<int> Weekdays_Between_Two_Dates_END_IS_PLUS_1 { get; set; }
		public Nullable<int> Weekdays_Between_Two_Dates_SAME_DAY { get; set; }
		public Nullable<decimal> Weekly_Rate { get; set; }
		public string Workflow_Notes_calculated_default_Value { get; set; }
		public string Workflow_Notes_default_Value { get; set; }
		public string Workflow_Notes_no_default_value { get; set; }
		public Nullable<decimal> Workflow_Numeric_Value { get; set; }
		public string Working_Pattern { get; set; }
		public byte[] TimeStamp { get; set; }
	}
}
